services:
  api:
    container_name: checkout-microservice
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/techchallenge-app/checkout-microservice
    ports:
      - 3002:3002
    volumes:
      - ./:/usr/src/techchallenge-app/checkout-microservice
      - /usr/src/techchallenge-app/checkout-microservice/node_modules
    command: sh -c "npm run start:dev"
   
  
